const { app, BrowserWindow, ipcMain, shell, dialog } = require('electron');
const path = require('node:path');
const fs = require('node:fs/promises');
const { LocalStorageService, collections } = require('./storage/LocalStorageService.cjs');
const { AuthService } = require('./storage/AuthService.cjs');
let mainWindow, storage, auth;
async function boot(){ app.setName('Salon Management'); storage=new LocalStorageService(app.getPath('userData')); await storage.initialize(); auth=new AuthService(storage); createWindow(); }
function createWindow(){ mainWindow=new BrowserWindow({width:1440,height:900,minWidth:1100,minHeight:700,title:'Salon Management',webPreferences:{preload:path.join(__dirname,'preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true}}); mainWindow.removeMenu(); if(process.env.VITE_DEV_SERVER_URL) mainWindow.loadURL(process.env.VITE_DEV_SERVER_URL); else mainWindow.loadFile(path.join(__dirname,'../dist/index.html')); }
app.whenReady().then(boot); app.on('window-all-closed',()=>{ if(process.platform!=='darwin') app.quit(); }); app.on('activate',()=>{ if(BrowserWindow.getAllWindows().length===0) createWindow(); });
const ok=(v)=>({ok:true,data:v}); const bad=(e)=>({ok:false,error:e.message||'Unexpected desktop error'});
ipcMain.handle('storage:invoke',async (_e,{method,entity,args=[]})=>{ try{ if(!collections[entity]) throw new Error('Unsupported collection'); if(!['getAll','getById','create','update','delete','replaceAll','clear','filter'].includes(method)) throw new Error('Unsupported storage method'); return ok(await storage[method](entity,...args)); }catch(e){return bad(e)} });
ipcMain.handle('auth:invoke',async (_e,{method,args=[]})=>{ try{ if(!['hasUsers','register','login','me','logout','changePassword'].includes(method)) throw new Error('Unsupported auth method'); return ok(await auth[method](...args)); }catch(e){return bad(e)} });
ipcMain.handle('app:invoke',async (_e,{method,args=[]})=>{ try{ if(method==='getDataPath') return ok(app.getPath('userData')); if(method==='openDataFolder') return ok(await shell.openPath(app.getPath('userData'))); if(method==='openBackupFolder') return ok(await shell.openPath(storage.backupPath)); if(method==='print') return ok(await mainWindow.webContents.print({silent:false,printBackground:true})); throw new Error('Unsupported app method'); }catch(e){return bad(e)} });
ipcMain.handle('backup:invoke',async (_e,{method,args=[]})=>{ try{ if(method==='create') return ok(await storage.createBackup()); if(method==='list') return ok(await storage.listBackups()); if(method==='restore') return ok(await storage.restoreBackup(args[0])); if(method==='export'){ const result=await dialog.showSaveDialog(mainWindow,{title:'Export Backup',defaultPath:`SalonBackup_${new Date().toISOString().slice(0,10)}.json`,filters:[{name:'Salon Backup',extensions:['json']}]}); if(result.canceled) return ok({canceled:true}); const data={exported_at:new Date().toISOString(),collections:{}}; for(const e of Object.keys(collections)) data.collections[e]=await storage.read(e); await fs.writeFile(result.filePath,JSON.stringify(data,null,2),'utf8'); return ok({path:result.filePath}); } if(method==='import'){ const result=await dialog.showOpenDialog(mainWindow,{title:'Import Backup',filters:[{name:'Salon Backup',extensions:['json']}],properties:['openFile']}); if(result.canceled) return ok({canceled:true}); const parsed=JSON.parse(await fs.readFile(result.filePaths[0],'utf8')); if(!parsed.collections) throw new Error('Invalid backup package'); await storage.createBackup(`pre-import-${Date.now()}`); for(const e of Object.keys(collections)) if(parsed.collections[e]) await storage.replaceAll(e,parsed.collections[e]); return ok({success:true}); } throw new Error('Unsupported backup method'); }catch(e){return bad(e)} });
